INSERT INTO PERSON(DTYPE, USER_NAME) VALUES('User', 'Joao');
INSERT INTO PERSON(DTYPE, USER_NAME) VALUES('User', 'Pedro');
INSERT INTO PERSON(DTYPE, USER_NAME) VALUES('Seller', 'Murilo');
INSERT INTO PERSON(DTYPE, USER_NAME) VALUES('Seller', 'Wagner');
INSERT INTO PERSON(DTYPE, USER_NAME) VALUES('Seller', 'Larissa');
INSERT INTO PERSON_FOLLOWING VALUES(1, 3);
INSERT INTO PERSON_FOLLOWING VALUES(1, 4);
