INSERT INTO PERSON(DTYPE, USER_NAME, FOLLOWERS_COUNT) VALUES('User', 'Joao', 1);
INSERT INTO PERSON(DTYPE, USER_NAME, FOLLOWERS_COUNT) VALUES('User', 'Pedro', 1);
INSERT INTO PERSON(DTYPE, USER_NAME, FOLLOWERS_COUNT) VALUES('Seller', 'Murilo', 1);
INSERT INTO PERSON(DTYPE, USER_NAME, FOLLOWERS_COUNT) VALUES('Seller', 'Wagner', 1);
INSERT INTO PERSON(DTYPE, USER_NAME, FOLLOWERS_COUNT) VALUES('Seller', 'Larissa', 0);
INSERT INTO PERSON_FOLLOWING VALUES(1, 3);
INSERT INTO PERSON_FOLLOWING VALUES(1, 4);
INSERT INTO PERSON_FOLLOWERS VALUES(4, 1);
INSERT INTO PERSON_FOLLOWERS VALUES(3, 1);